# Generated by Django 6.0.4 on 2026-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_1', models.TextField(blank=True, null=True)),
                ('f_2', models.TextField(blank=True, null=True)),
                ('f_3', models.TextField(blank=True, null=True)),
                ('f_4', models.TextField(blank=True, null=True)),
                ('f_5', models.TextField(blank=True, null=True)),
                ('f_6', models.TextField(blank=True, null=True)),
                ('f_7', models.TextField(blank=True, null=True)),
                ('f_8', models.TextField(blank=True, null=True)),
                ('f_9', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback Response',
                'verbose_name_plural': 'Feedback Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
