# Generated by Django 6.0.4 on 2026-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_survey', '0002_feedbackresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='opq_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_11',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_12',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_13',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_14',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_15',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_16',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_17',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_18',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_19',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rq_20',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
