# Generated by Django 6.0.4 on 2026-05-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_survey', '0003_delete_feedbackresponse_surveyresponse_opq_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='human_likeness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
