# Generated by Django 6.0.4 on 2026-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageranking',
            name='session_id',
            field=models.CharField(default='legacy', max_length=255),
        ),
        migrations.AlterField(
            model_name='imageranking',
            name='image_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='imageranking',
            unique_together={('session_id', 'image_name')},
        ),
    ]
